name: Supabase Keep Alive

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  ping-supabase:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase Database
        env:
          SUPABASE_URL: https://lpfhbuxgjmpdmoygnnlw.supabase.co/rest/v1/members
          SUPABASE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxwZmhidXhnam1wZG1veWdubmx3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODI5MDU0MjMsImV4cCI6MjA5ODQ4MTQyM30.jYTDZ5nzTSgcNU-jcbsSknSdLGTSuqEOMe63EtV1Yks
        run: |
          curl -X GET "https://lpfhbuxgjmpdmoygnnlw.supabase.co/rest/v1/users?select=*&limit=1" \
          -H "apikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxwZmhidXhnam1wZG1veWdubmx3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODI5MDU0MjMsImV4cCI6MjA5ODQ4MTQyM30.jYTDZ5nzTSgcNU-jcbsSknSdLGTSuqEOMe63EtV1Yks" \
          -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxwZmhidXhnam1wZG1veWdubmx3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODI5MDU0MjMsImV4cCI6MjA5ODQ4MTQyM30.jYTDZ5nzTSgcNU-jcbsSknSdLGTSuqEOMe63EtV1Yks"
